# -*- coding: utf-8 -*-
"""2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11vqYDCKHGuq479eSFQtKM1h6utKQRKxb
"""

import requests
from bs4 import BeautifulSoup
import prettytable

r = requests.get('https://www.cwb.gov.tw/V8/C/W/TemperatureTop/County_TMax_T.html?ID=Tue%20Apr%2004%202023%2020:21:19%20GMT+0800%20(%E5%8F%B0%E5%8C%97%E6%A8%99%E6%BA%96%E6%99%82%E9%96%93)l')
b = r.text

soup = BeautifulSoup(b, 'html.parser')
tr_list = soup.find_all('tr')

t = PrettyTable(['地區', '氣溫'])
t.align['地區'] = 'l'
t.align['氣溫'] = 'r'

for tr in tr_list:
    th = tr.find('th', {'scope': 'row'})
    if th is not None:
        td = th.find_next('td')
        span = td.find('span', {'class': 'tem-C is-active'})
        if span is not None:
            t.add_row([th.text, span.text])

print(t)