# -*- coding: utf-8 -*-
"""1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOELUSGLmER7Dz2uxa60Y4x12t92-kBW
"""

import requests
import json
from prettytable import PrettyTable

keywords = input('關鍵字:')
# i=input('前往頁碼')

url = 'https://ecshweb.pchome.com.tw/search/v3.3/all/results'
for i in range(1,6,1):
  params = {'q': keywords,
            'page':i,
            'sort': 'sale/dc'}

  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'}
r = requests.get(url, params=params, headers=headers)
d = json.loads(r.text)

t = PrettyTable(['商品名稱', '價格名稱'], encoding='utf-8')
t.align['商品名稱'] = 'l'
t.align['價格名稱'] = 'r'

for prod in d['prods']:
    t.add_row([prod['name'], prod['price']])


for prod in d[prods]:
    t.add_row([prod])
print(t)
